app/article/forms.py
# Import packages
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class ArticleForm(FlaskForm):
	"""
	Form for article to add or edit
	"""
	title = StringField('Title',  validators=[DataRequired()])
	description = StringField('Description')
	submit = SubmitField('Submit')
	

app/__init__.py
# Import packages
from flask import abort, Flask, render_template
import boto3
import os
from config import app_config

# Create DynamoDb instance
dynamodb = boto3.resource('dynamodb', region_name='us-west-2', endpoint_url="http://localhost:8000")

def create_app(config_name):
	# Create application instance
	app = Flask(__name__, instance_relative_config=True)

	# Load config based on environment
	app.config.from_object(app_config[config_name])
	app.config.from_pyfile('config.py')

	try:
		# Create DynamoDb table articles
		table = dynamodb.create_table(
		    TableName='articles',
		    KeySchema=[
		        {
		            'AttributeName': 'article_id',
		            'KeyType': 'HASH'
		        }
		    ],
		    AttributeDefinitions=[
		        {
		            'AttributeName': 'article_id',
		            'AttributeType': 'S'
		        }

		    ],
		    ProvisionedThroughput={
		        'ReadCapacityUnits': 1,
		        'WriteCapacityUnits': 1
		    }
		)
	except Exception as exception:
		pass

	from .article import article as article_blueprint
	app.register_blueprint(article_blueprint)

	return app

app/article/__init__.py
from flask import Blueprint

article = Blueprint('article', __name__)

from . import views

app/article/views.py
# Import packages
from flask import flash, request, redirect, render_template, url_for
import uuid

from . import article
from .. import dynamodb
from .forms import ArticleForm

table = dynamodb.Table('articles')

@article.route('/create', methods=['GET', 'POST'])
def create():
    """
    Method to create article
    """
    form = ArticleForm(request.form)

    # Check request method and validate form
    if request.method == 'POST' and form.validate():
        data = {}
        data['article_id'] = uuid.uuid4().hex
        data['title'] = form.title.data
        data['description'] = form.description.data

        data = dict((k, v) for k, v in data.items() if v)

        # Save data in DynamoDb table
        response = table.put_item(Item=data)

        if response:
            flash('Article is successfully added')
            return redirect(url_for('article.list'))

    return render_template('article/form.html', add_article=True,
                           form=form, title='Add Article')

@article.route('/edit/<string:article_id>', methods=['GET', 'POST'])
def edit(article_id):
    """
    Method to edit article
    """
    response = table.get_item(
        Key={'article_id': article_id}
        )
    data = response.get('Item')

    if data is None:
        flash('Unable to get Article')
        return redirect(url_for('article.list'))

    form = ArticleForm(title=data.get('title'), description=data.get('description'))

    # Check request method and validate form
    if request.method == 'POST' and form.validate():
        data = {}
        data['article_id'] = article_id
        data['title'] = form.title.data
        data['description'] = form.description.data

        data = dict((k, v) for k, v in data.items() if v)

        # Save data in DynamoDb to update table
        response = table.put_item(Item=data)

        if response:
            flash('Article is successfully updated')
            return redirect(url_for('article.list'))
    
    return render_template('article/form.html', add_article=False,
                           form=form, title='Edit Article', article_id=article_id)


@article.route('/delete/<string:article_id>', methods=['GET'])
def delete(article_id):
    """
    Method to delete articles
    """
    response = table.get_item(
        Key={'article_id': article_id}
        )
    data = response.get('Item')
    if data is None:
        flash('Unable to get Article')
        return redirect(url_for('article.list'))    

    # Delete article for a particular id
    response = table.delete_item(
        Key={'article_id':article_id}
        )

    if response:
            flash('Article is successfully deleted')

    return redirect(url_for('article.list'))

@article.route('/list', methods=['GET'])
def list():
    """
    Method to list articles
    """
    articles = []
    if request.method == 'GET':
        # Get all articles
        response = table.scan()
        articles = response.get('Items')

    return render_template('article/articles.html', articles=articles, title='List Articles')

app/templates/article/articles.html
{% extends "base.html" %}
{% block title %}
    {{ title }}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            <h1>List Articles</h1>
            <br/>
            {% with messages=get_flashed_messages() %}
                {% if messages %}
                <ul class="flashes">
                {% for message in messages %}
                <li>{{ message|safe }}</li>
                {% endfor %}
                </ul>
                {% endif %}
            {% endwith %}
            <ul>
                {% for article in articles %}
                    <li>{{ article.get('title') }} 
                    | <a href="{{ url_for('article.edit', article_id=article.get('article_id')) }}">edit</a> 
                    | <a href="{{ url_for('article.delete', article_id=article.get('article_id')) }}">delete</a>
                    </li>
                {% else %}
                No Articles found
                {% endfor %}
            </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/article/form.html
{% extends "base.html" %}
{% block title %}
    {{ title }}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_article %}
                <h1>Add Article</h1>
                <br/>
                <form action="{{ url_for('article.create') }}" method="POST">
            {% else %}
                <h1>Edit Article</h1>
                <br/>
                <form action="{{ url_for('article.edit', article_id=article_id) }}" method="POST">
            {% endif %}

            {% if form.errors %}
            <ul class=errors>
            {% for error in form.errors %}
            <li>{{ error }}</li>
            {% endfor %}
            </ul>
            {% endif %}

            {{ form.csrf_token }}
            
            {{ form.title }}
            {{ form.description }}
            {{ form.submit }}
            

            </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

</head>
<body>
    <div class="wrapper">
      {% block body %}
      {% endblock %}     
    </div>
</body>
</html>